
data_ingestion:  
  bucket_name: my-bucket752
  bucket_file_names: 
    - 'anime.csv'
    - 'animelist.csv'
    - 'anime_with_synopsis.csv'


model:
  embedding_size: 128
  loss: binary_crossentropy
  optimizer: Adam
  metrics:
    - mae
    - mse